apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: gitlab-config
  namespace: flux-system
spec:
  dependsOn:
    - name: gitlab
  interval: 1h
  retryInterval: 1m
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system # must match your existing GitRepository
    namespace: flux-system
  path: ./gitlab-config/
  prune: true
  wait: true
  postBuild:
    substitute:
      var_substitution_enabled: "true"
      cluster_name: "home"
