apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - flux-system
  - cert-manager.yml
  - cert-manager-config.yml
  - metal-lb.yml
  - metal-lb-config.yml
  - istio.yml
  - istiod.yml
  - istio-config.yml
