---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: metal-lb-config
  namespace: flux-system
spec:
  dependsOn:
    - name: metal-lb
  interval: 1h
  retryInterval: 1m
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./metal-lb-config/
  prune: true
  wait: true
  postBuild:
    substitute:
      var_substitution_enabled: "true"
      cluster_name: "home"
